Add `azurerm_postgresql_configuration` resources to the module
claranet/terraform-azurerm-postgresql pull request #1
Opened 2019-01-23 10:09 UTC by Shr3ps

2019-01-23 10:30 UTC, pdecat commented
Why is this PR targeting the fork instead of upstream?

2019-01-23 10:32 UTC, BzSpi approved these changes

2019-01-23 13:49 UTC, Shr3ps commented
> 
> 
> Why is this PR targeting the fork instead of upstream?

You right, so I rebased to the upstream master and opened the upstream PR: https://github.com/Azure/terraform-azurerm-postgresql/pull/14

2019-02-06 09:34 UTC, pdecat requested changes
To close.

2019-02-06 10:03 UTC, closed without merging